#!/usr/bin/env sh
yabai -m config layout bsp
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# global settings
#yabai -m config mouse_follows_focus on            
#yabai -m focus_follows_mouse on            
yabai -m window_animation_duration    0.0
# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Finder$" manage=off
echo "yabai configuration loaded.."
